// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe6fwyDy_733RenLz-zGwFXfTnXND6tkI',
    appId: '1:574694385709:web:39c769e8634b71c30bb0a4',
    messagingSenderId: '574694385709',
    projectId: 'attendify-dc44d',
    authDomain: 'attendify-dc44d.firebaseapp.com',
    storageBucket: 'attendify-dc44d.firebasestorage.app',
    measurementId: 'G-SL9SFJSYBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG0XWU4XF6VRAYrNCqSOKIyIBpFYQt68Q',
    appId: '1:574694385709:android:c4d4ca1cbf749d820bb0a4',
    messagingSenderId: '574694385709',
    projectId: 'attendify-dc44d',
    storageBucket: 'attendify-dc44d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGnkGo5HDayEbWh7zER9cgozjwPtcjMrM',
    appId: '1:574694385709:ios:2fb158693697097c0bb0a4',
    messagingSenderId: '574694385709',
    projectId: 'attendify-dc44d',
    storageBucket: 'attendify-dc44d.firebasestorage.app',
    androidClientId: '574694385709-g6gp8a04bib29o1pt2ohnpklr3dhab9j.apps.googleusercontent.com',
    iosClientId: '574694385709-dtaefa4gt44v2jnamcb3t09ll9lharrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGnkGo5HDayEbWh7zER9cgozjwPtcjMrM',
    appId: '1:574694385709:ios:2fb158693697097c0bb0a4',
    messagingSenderId: '574694385709',
    projectId: 'attendify-dc44d',
    storageBucket: 'attendify-dc44d.firebasestorage.app',
    androidClientId: '574694385709-g6gp8a04bib29o1pt2ohnpklr3dhab9j.apps.googleusercontent.com',
    iosClientId: '574694385709-dtaefa4gt44v2jnamcb3t09ll9lharrh.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe6fwyDy_733RenLz-zGwFXfTnXND6tkI',
    appId: '1:574694385709:web:eab4056a09f84b8b0bb0a4',
    messagingSenderId: '574694385709',
    projectId: 'attendify-dc44d',
    authDomain: 'attendify-dc44d.firebaseapp.com',
    storageBucket: 'attendify-dc44d.firebasestorage.app',
    measurementId: 'G-TJD27G70M8',
  );

}